- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Install Python3"
  become: true
  shell:
    apt install -y python3

- name: "Install nodejs and dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present