- name: Create directory
  file:
    path: ~/deploy
    state: directory

- name: Unarchive udapeople.tar.gz
  unarchive:
    src: ../../backend/udapeople.tar.gz
    dest: ~/deploy/

- name: Start PM2
  shell: |
    cd ~/deploy/
    npm i
    pm2 start main.js --update-env