- name: Create directory
  file:
    path: ~/deploy
    state: directory

- name: Find
  find:
    paths: ../../backend
    recurse: yes

- name: Find 2
  find:
    paths: /root/project
    recurse: yes

- name: Unarchive udapeople.tar.gz
  unarchive:
    src: ../../backend/udapeople.tar.gz
    dest: ~/deploy/
    remote_src: True
    mode: 0777

- name: Start PM2
  shell: |
    cd ~/deploy/
    npm i
    pm2 start main.js --update-env