- name: Create directory
  file:
    path: ~/deploy
    state: directory

- name: Copy files
  become: true
  copy:
    src: /home/udapeople.tar.gz
    dest: /home/ubuntu/udapeople.tar.gz

- name: Unarchive udapeople.tar.gz
  unarchive:
    src: /home/ubuntu/udapeople.tar.gz
    dest: ~/deploy/
    remote_src: yes

- name: Start PM2
  shell: |
    cd ~/deploy/
    npm i
    pm2 start npm --name backend -- start