- name: Create directory
    file:
      path: ~/deploy
      state: directory

- name: Start PM2
  shell: |
    tar -xvf /home/circleci/project/backend/udapleople.tar.gz -C ~/deploy/
    cd ~/deploy/
    npm i
    pm2 start main.js --update-env